name: Docker Image CI

on:
  push:
    branches:
      - '*'

# Only the most recent commit is executed in CI at any given time
# If a new run is triggered for the same workflow and branch/tag, any currently running workflow in that group will be canceled
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: andreo141
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push latest
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            wolfderechter/suncatcher:latest
